### ISSUE TITLE
Cannot read property 'includes' of null

### ISSUE THREAD

**Issue by sklawren** [americanexpress/amex-jest-preset#5]
There's a bug when you run this and a simple fix.

```bash
TypeError: Cannot read property 'includes' of null
    at test.failureMessages.forEach (/Users/sklawren/Code/amex/gustave/axp-gustave-root/node_modules/amex-jest-preset/html-report-creator.js:82:39)
    at Array.forEach (<anonymous>)
    at suite.testResults.forEach (/Users/sklawren/Code/amex/gustave/axp-gustave-root/node_modules/amex-jest-preset/html-report-creator.js:79:34)
    at Array.forEach (<anonymous>)
```

I cannot commit to this repo because npm install won't run while on the VPN, and all my proxy settings won't let me run while off the VPN.

Here's the fix.

Replace this:
https://github.com/americanexpress/amex-jest-preset/blob/master/html-report-creator.js#L81-L86

With this:
```javascript
if (plainFailureMessage) {
  // TODO: need to find better way to when it is an image snapshot
  if (plainFailureMessage.includes('__image_snapshots__/')) {
    const imageDiffUrl = `${plainFailureMessage.match(':(.*).png')[1]}.png`;
    failureMsgDiv.ele('a', {href: imageDiffUrl});
  }
  failureMsgDiv.ele('pre', plainFailureMessage);
}
```

**Comment by anescobar1991** [comment]
Fixed with #6

Thanks @sklawren
